# Generated by Django 3.2 on 2022-08-19 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='cycle_id')),
                ('cycle_name', models.CharField(max_length=45)),
                ('limit_at', models.CharField(blank=True, default='0', max_length=45, null=True)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('is_cycle', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='pet_id')),
                ('pet_name', models.CharField(max_length=45, verbose_name='pet_name')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=45)),
                ('code', models.CharField(default=pets.models.generate_random_slug_code, editable=False, max_length=45, unique=True, verbose_name='code')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('master', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='prescription_id')),
                ('hospital', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('create_dt', models.DateField()),
                ('pet_id', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='event_id')),
                ('event_name', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('is_clear', models.BooleanField(default=False)),
                ('pet_id', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='CycleDetail',
            fields=[
                ('detail_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='detail_id')),
                ('detail_name', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.CharField(default='00:00', max_length=45)),
                ('cycle_id', models.ForeignKey(db_column='cycle_id', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='pets.cycle')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='pet_id',
            field=models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.CreateModel(
            name='ActiveImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='image_id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption', models.CharField(blank=True, max_length=45, null=True, verbose_name='caption')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pet_id', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='active_img', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='AchieveCycle',
            fields=[
                ('achieve_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='achieve_id')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('detail_id', models.ForeignKey(db_column='detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='pets.cycledetail')),
            ],
        ),
    ]
