# Generated by Django 3.2 on 2022-08-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
