# Generated by Django 3.2 on 2022-08-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
