# Generated by Django 3.2 on 2022-09-17 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='user_id')),
                ('username', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=45, unique=True)),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
